### ISSUE TITLE
Unclear License

### ISSUE THREAD

**Issue by pecorarista** [mastermay/text-autospace.js#1]
I'm interested in your product, and would like to use it in my web pages.
However, the license is not clearly stated.
Could you put a LICENSE file in this repository, or add information in your code?

**Comment by pecorarista** [comment]
In addition, creating `package.json` will help users install your product easily via package managers such as npm, bower, or yarn.

**Comment by mastermay** [comment]
recommend this repo https://github.com/ethantw/Han :)

**Comment by pecorarista** [comment]
Thank you for the recommendation!
